# TODO distribute library loading to appropriate files
library(readxl)
library(readr)
library(colorspace)
library(RColorBrewer)
library(viridis)
library(ggplot2)
library(ggrepel)
library(VennDiagram)
library(ComplexHeatmap)
library(pheatmap)
library(cowplot)
library(circlize)
library(cummeRbund)
library(DESeq2)
library(limma)
library(matrixStats)
library(broom)
library(stringr)
library(tibble)
library(purrr)
library(dplyr)

pack = c("readxl", 
         "readr", 
         "colorspace", 
         "RColorBrewer", 
         "viridis", 
         "ggplot2", 
         "ggrepel", 
         "VennDiagram", 
         "ComplexHeatmap", 
         "pheatmap", 
         "cowplot", 
         "circlize", 
         "cummeRbund", 
         "DESeq2", 
         "limma", 
         "matrixStats", 
         "broom", 
         "stringr", 
         "tibble", 
         "purrr", 
         "dplyr")